---
title: "Untitled"
author: "Jason Torres"
date: "December 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup 


```{r}
"%&%" <- function(a,b) paste0(a,b)

library("data.table")
library("tidyverse")
library("gridExtra")
library("grid")

server.dir <- "/home/jason/science/servers/FUSE/"

work.dir <- server.dir %&% "projects/mv-compare/"
input.dir <- work.dir %&% "input_files/"
output.dir <- work.dir %&% "output_files/"

known.genefile <- input.dir %&% "causal_genes3.txt"
metab.old.df <- fread(known.genefile)
plot.dir <- work.dir %&% "plots/"


mtxn.df <- fread(input.dir %&% "metaxcan_full_results_filtered_for_model_fit_and_pval_at_0.01.txt")

hmdb.df <- fread(work.dir %&% "hmdb/hmdb.txt")
#causal.df <- fread(input.dir %&% "causal_genes3.txt")

```


Prepare updated metab.df 


```{r}

#s2.df <- fread(input.dir %&% "shin_supplemetary_tables_tableS2_3cols.txt") #%>% dplyr::select(.,one_of("V2","V3")) %>% as.data.frame(.)
#s6.df <- fread(input.dir %&% "shin_supplemetary_tables_tableS6.txt")

#make_metab_df <- function(){
#  sub.df <- dplyr::select(s6.df,one_of("Most associated metabolite or ratio","Predicted causal gene"))
#  sub.df <- sub.df[!duplicated(sub.df),] %>% as.data.frame(.)
#  pb <- txtProgressBar(min=0,max=dim(sub.df)[1],style=3)
#  out.df <- c()
#  for (i in 1:dim(sub.df)[1]){
#    setTxtProgressBar(pb,i)
#    metab <- sub.df$`Most associated metabolite or ratio`[i] 
#    pcg <- sub.df$`Predicted causal gene`[i]
#    #mid <- ifelse(length(filter(s2.df,V3==metab)$V2)==0,NA,filter(s2.df,V3==metab)$V2)
#    mid <- ifelse(length(filter(s2.df,Status==metab)$`Metabolite`)==0,NA,filter(s2.df,Status==metab)$`Metabolite`)
#    build.df <- data.frame(metabolite=metab,predicted_causal=pcg,MetaboID=mid,stringsAsFactors = FALSE)
#    out.df <- rbind(out.df,build.df)
#  }
#  out.df <- filter(out.df,!(grepl("/",metabolite)),!grepl("X-",metabolite),predicted_causal!="unknown",predicted_causal!="")
#  ##out.df <- filter(out.df,!grepl("X-",metabolite),predicted_causal!="unknown",predicted_causal!="")
#  out.df$MetaboID[out.df$metabolite=="Alpha-hydroxyisovalerate"] <- "M33937"
#  out.df$metabolite[out.df$metabolite=="Alpha-hydroxyisovalerate"] <- "alpha-hydroxyisovalerate"
#  out.df$MetaboID[out.df$metabolite=="Serine"] <- "M32315"
#  out.df$metabolite[out.df$metabolite=="Serine"] <- "serine"
#  out.df$MetaboID[out.df$metabolite=="1-palmitoylglycero-phosphoethanolamine"] <- "M35631"
#  out.df$metabolite[out.df$metabolite=="1-palmitoylglycero-phosphoethanolamine"] <- "1-palmitoylglycerophosphoethanolamine"
#  out.df$MetaboID[out.df$metabolite=="HWESASXX"] <- "M32836"
#  out.df <- out.df[!duplicated(out.df),]
#}

#metab.df <- make_metab_df()


```



```{r}

metab.df <- fread(input.dir %&% "metabolite_GWAS_genes_from-Anne.txt")
names(metab.df) <- c("gene_name","metabolite","MetaboID","predicted_causal")


```



```{r}


mtxn.df$predicted_causal <- map(1:dim(mtxn.df)[1],function(i){
  m <- mtxn.df$metabolite[i]
  g <- mtxn.df$gene_name[i]
  val <- filter(metab.df,gene_name==g,predicted_causal!="unknown",MetaboID==m)$predicted_causal # g %in% 
  ifelse(length(val)>0,val,"-")
  }) %>% as.character(.)
  #as.logical(.)

mtxn.df$gwas.unknown <- map(1:dim(mtxn.df)[1],function(i){
  m <- mtxn.df$metabolite[i]
  g <- mtxn.df$gene_name[i]
  val <- filter(metab.df,gene_name==g,predicted_causal=="unknown",MetaboID==m)$gene_name # g %in% 
  ifelse(length(val)>0,val,"-")
  }) %>% as.character(.)
  #as.logical(.)

mtxn.df$hmdb <- map(mtxn.df$gene_name,function(g){g %in% hmdb.df$gene_name}) %>% 
  as.logical(.)

sub <- dplyr::select(mtxn.df,one_of("gene_name","metabolite","predicted_causal","gwas.unknown","hmdb")); sub <- sub[!duplicated(sub),]
dim(sub) # 826 



dim(filter(sub,gene_name==predicted_causal,hmdb==FALSE))[1] # 1 predicted causal gene, SLC16A9 (for M15500 and M32412) not in HMDB
filter(sub,gene_name==predicted_causal,hmdb==TRUE)$gene_name %>% unique(.) %>% length(.) # 34 known genes in HMDB
dim(filter(sub,gene_name==gwas.unknown,hmdb==FALSE))[1] #  6 of the gwas unknown genes are NOT in HMDB
filter(sub,gene_name==gwas.unknown,hmdb==TRUE)$gene_name %>% unique(.) %>% length(.) # 4 of the gwas unknown genes are in HMDB


#sum(metab.df$predicted_causal %in% hmdb.df$gene_name)
#metab.df$predicted_causal[!(metab.df$predicted_causal%in% hmdb.df$gene_name)]


novel.df <- filter(sub,predicted_causal==FALSE,hmdb==TRUE)


filter(sub,gene_name!=predicted_causal) %>% dim(.) # 785 (704 genes) novel gene/metabolite pairs 
#filter(sub,gene_name!=predicted_causal)$gene_name %>% unique(.) %>% length(.)
filter(sub,gene_name!=predicted_causal,hmdb==TRUE) %>% dim(.) # 212 (189 genes) of the novel gene/metabolite pairs are in HMDB
# 212/785 = 27%, 189/704 = 0.268
#filter(sub,gene_name!=predicted_causal,hmdb==TRUE)$gene_name %>% unique(.) %>% length(.) # 
filter(sub,gene_name!=predicted_causal,gene_name==gwas.unknown,hmdb==TRUE) %>% dim(.) # 4 pairs of which (corresponding to 4 unique genes) are in HMDB and are gwas.unknown 




dim(filter(metab.df,predicted_causal!="unknown"))[1] # 61
dim(filter(metab.df,predicted_causal=="unknown"))[1] # 18


```



```{r}


get_metab_annot <- function(query.gene){
  q.df <- filter(hmdb.df,gene_name==query.gene)
  if (dim(q.df)[1] > 0){
    go.vec <- strsplit(q.df$go_classifications,split="GO:\\d+",fixed=FALSE)[[1]]
    go.ids <- regmatches(q.df$go_classifications, gregexpr("GO:\\d+", q.df$go_classifications))[[1]]
    path.vec <- strsplit(q.df$pathways,split="map\\d{5}",fixed=FALSE)[[1]] %>% 
      map(.,function(s){strsplit(s,split="SMP\\d{5}",fixed=FALSE)[[1]]}) %>% unlist(.)
    return(list(go.ids,path.vec))    
  } 
  else{
    return(list(NA,NA))
  }
}

#get_metab_annot("NT5C1B")

group_metab_assoc_genes <- function(metab){
  gene.vec <- filter(mtxn.df,metabolite==metab)$gene_name %>% unique(.)
  known.vec <- gene.vec[gene.vec %in% filter(metab.df,MetaboID==metab)$predicted_causal]
  novel.vec <- gene.vec[!(gene.vec %in% filter(metab.df,MetaboID==metab)$predicted_causal)]
  return(list(known.vec,novel.vec))
}

compare_gene_annotations <- function(gene1,gene2,annot.num){
  # annot.num = 1; use GO IDs 
  # annot.num = 2; use hmdb pathway names 
  g1 <- get_metab_annot(gene1)[[annot.num]]
  g2 <- get_metab_annot(gene2)[[annot.num]]
  overlap <- intersect(g1,g2)
  if (length(overlap)==0){
    return("None")
  } else{
    return(overlap)
  }
}

build_single_metab_df <- function(metab,alt=FALSE){
  l <- group_metab_assoc_genes(metab)  
  known.vec <- l[[1]]
  novel.vec <- l[[2]]

  out.df <- c()
  k.df <- data.frame(Gene=known.vec,
                     Group=rep("known",length(known.vec)),
                     go.shared.known=rep("-",length(known.vec)),
                     path.shared.known=rep("-",length(known.vec)),
                     stringsAsFactors = FALSE)
  out.df <- rbind(out.df,k.df)
  
  if (alt==TRUE){
    known.vec <- filter(metab.df,MetaboID==metab)$predicted_causal %>% unique(.)
  }
  known.goids <- map(known.vec,function(k){get_metab_annot(k)[[1]]}) %>% unlist(.) %>% unique(.) %>% na.omit(.)
  known.paths <- map(known.vec,function(k){get_metab_annot(k)[[2]]}) %>% unlist(.) %>% unique(.) %>% na.omit(.)  
  
  for (n in novel.vec){
    #print(n)
    go.ids <- get_metab_annot(n)[[1]]
    path.ids <- get_metab_annot(n)[[2]]
    
    path.eval <- any(path.ids %in% known.paths)==TRUE
    if (path.eval==FALSE & length(path.ids) > 0 & is.na(path.ids) ==FALSE){
      eval.vec <- c(unlist(map(path.ids,function(id){grepl(id,known.paths,fixed=TRUE)})),
                    unlist(map(known.paths,function(id){grepl(id,path.ids,fixed=TRUE)})))
      if (any(eval.vec)==TRUE){
        path.eval=TRUE
      }else{
        path.eval=FALSE
      }
    }
    
    build.df <- data.frame(Gene=n,
                     Group="novel",
                     go.shared.known=any(go.ids %in% known.goids)==TRUE,
                     path.shared.known=path.eval,
                     stringsAsFactors = FALSE)
    out.df <- rbind(out.df,build.df)
  }
  out.df <- data.frame(Metabolite=rep(metab,dim(out.df)[1]),out.df)
  return(out.df)
}

build_full_metab_df <- function(alt=FALSE){
  metab.vec <- unique(mtxn.df$metabolite)
  out.df <- c()
  pb <- txtProgressBar(min=0,max=length(metab.vec),style=3)
  for (i in 1:length(metab.vec)){
    setTxtProgressBar(pb,i)
    metab <- metab.vec[i]
    #print(metab)
    build.df <- build_single_metab_df(metab,alt)
    out.df <- rbind(out.df,build.df)
  }
  out.df$Metabolite <- as.character(out.df$Metabolite)
  return(out.df)
}

full.df <- build_full_metab_df(alt=TRUE)


```



# Make results tables 

## Table 1: Profile of MetaXcan results for known metabolite genes

```{r}

#library(gridExtra)
#library(grid)

make_table_1 <- function(){
  pb <- txtProgressBar(min=0,max=dim(metab.df)[1],style=3)
  top.q <- c()
  top.tissue <- c()
  num.tissues <- c()
  
  for (i in 1:dim(metab.df)[1]){
    setTxtProgressBar(pb,i)
    metab <- metab.df$metabolite[i]
    g <- metab.df$predicted_causal[i]
    id <- metab.df$MetaboID[i]
    sub <- filter(mtxn.df,gene_name==g,metabolite_name==metab) %>% arrange(FDR_studywide)
    
    if (dim(sub)[1]==0){
      toptiss <- NA
      topq <- NA
      numtiss <- NA 
      
    } else{
      toptiss <- sub$Tissue[1]
      numtiss <- dim(sub)[1]
      topq <- sub$FDR_studywide[1]
    }
    top.q <- append(top.q,topq)
    top.tissue <- append(top.tissue,toptiss)
    num.tissues <- append(num.tissues,numtiss)
  }
  out.df <- dplyr::select(metab.df,one_of("MetaboID","metabolite","predicted_causal")) %>% as.data.frame(.)
  out.df$number.mtxn.assoc <- num.tissues
  out.df$most.sig.tissue <- top.tissue %>% as.character(.)
  out.df$most.sig.tissue <- gsub("_","-",out.df$most.sig.tissue)
  out.df$most.siq.qvalue <- top.q
  out.df <- arrange(out.df,desc(num.tissues))
  names(out.df) <- c("Metabolite ID","Metabolite Name","Causal Gene","Number of Gene\n Associations","Most Significant\nTissue","q-value")
  
  tt3 <- ttheme_minimal(
    core=list(bg_params = list(fill = blues9[1:2], col=NA),
            fg_params=list(fontface=3)),
    colhead=list(fg_params=list(col="navyblue", fontface=4L)),
    rowhead=list(fg_params=list(col="white", fontface=3L)))
  noNA.df <- na.omit(out.df)
  noNA.df$`q-value` <- map(noNA.df$`q-value`, function(n){signif(n,3)}) %>% as.numeric(.)
  grob2 <- tableGrob(noNA.df,theme=tt3)
  
  
  grid.draw(grob2)  
  
}


```


## Table 2: Profile of novel Metaxcan genes, for those that are annotated to same metabolic pathway as known metabolite genes, to what extent are they significant?



```{r}


slice<-function(x,n) { # https://stackoverflow.com/questions/2434833/how-can-i-partition-a-vector
    N<-length(x);
    lapply(seq(1,N,n),function(i) x[i:min(i+n-1,N)])
}

make_table_2_df  <- function(){
  
  
  # Subset to novel genes annotated in hmdb pathways 
  sub.df <- filter(mtxn.df,known==FALSE,hmdb==TRUE,metabolite%in%metab.df$MetaboID) %>% dplyr::select(one_of("gene","gene_name","metabolite","metabolite_name",
                                                                  "Tissue","zscore","pvalue","FDR_studywide"))
  pred.causal.gene <- c()
  shared.go.pathways <- c()
  shared.hmdb.pathways <- c() 
  pb <- txtProgressBar(min=0,max=dim(sub.df)[1],style=3)
  for (i in 1:dim(sub.df)[1]){
    #print(i)
    setTxtProgressBar(pb,i)
    g <- sub.df$gene_name[i]
    mid <- sub.df$metabolite[i]
    causal.genes.df <- filter(metab.df,MetaboID==mid)
    pcg <-  causal.genes.df$predicted_causal %>% paste(.,collapse=",")#map(causal.genes.df$predicted_causal,function(s){
      #vec <- strsplit(s,split=",")[[1]];sliced <- slice(vec,3)
      #map(sliced,function(vec){paste(vec,collapse=",")}) %>% unlist(.) %>% paste(.,collapse=",\n")
       #}) %>% as.character(.)
    query <- get_metab_annot(g)
    query.go <- query[[1]]
    query.hmdb <- query[[2]]
    reflists <-  ifelse(dim(causal.genes.df)[1]>0,map(1:length(causal.genes.df$predicted_causal), function(i){
      pc <- causal.genes.df$predicted_causal[i]
      metabs <- get_metab_annot(pc)
      return(metabs)
      }),NA)
    sgp <- ifelse(dim(causal.genes.df)[1]>0,map(1:length(reflists),function(i){ # 
      go.vec <- reflists[[i]][[1]]
      overlap <- go.vec[go.vec %in% query.go]
      if (length(overlap)==0){
        overlap <- NA
      }
      return(overlap)
    }) %>% unlist(.) %>% as.character(.)  %>% paste0(.,collapse=","),NA) 
    shp <- ifelse(dim(causal.genes.df)[1]>0,map(1:length(reflists),function(i){
      hmdb.vec <- reflists[[i]][[2]]
      overlap <- hmdb.vec[hmdb.vec %in% query.hmdb]
      if (length(overlap)==0){
        overlap <- NA
      }
      return(overlap)
    }) %>% unlist(.) %>% as.character(.) %>% paste0(.,collapse=","),NA)
    pred.causal.gene <- append(pred.causal.gene,pcg)
    shared.go.pathways <- append(shared.go.pathways,sgp)
    shared.hmdb.pathways <- append(shared.hmdb.pathways,shp)  
  }
  out.df <- cbind(sub.df,pred.causal.gene,shared.go.pathways,shared.hmdb.pathways)
  out.df$pred.causal.gene <- out.df$pred.causal.gene %>% as.character(.)
  out.df$shared.go.pathways <- out.df$shared.go.pathways %>% as.character(.)
  out.df$shared.hmdb.pathways <- out.df$shared.hmdb.pathways %>% as.character(.)
  out.df <- as.data.frame(out.df)
  out.df$shared.hmdb.pathways[out.df$shared.hmdb.pathways == "character(0)"] = "NA"

  out2.df <- c()
  for (i in 1:dim(out.df)[1]){
    sgp <- out.df$shared.go.pathways[i]
    shp <- out.df$shared.hmdb.pathways[i]
    if (sgp == "NA" & shp == "NA"){
      pass = 0 
    } else{
      out2.df <- rbind(out2.df,out.df[i,])
    }
    
  }
  return(out2.df)
}


tab2.df <- make_table_2_df()

tab2.df$Tissue <- gsub("_","-",tab2.df$Tissue)

write.table(tab2.df,output.dir%&%"novel_genes_sharing_pathways_with_known.txt",sep="\t",quote=FALSE,row.names=TRUE)


tab2.df$shared.go.pathways <- map(tab2.df$shared.go.pathways,function(s){
  vec <- strsplit(s,split=",")[[1]] 
  vec <- vec[vec !="NA"] 
  vec %>% length(.)}) %>% as.integer(.)
tab2.df$shared.hmdb.pathways <- map(tab2.df$shared.hmdb.pathways,function(s){
  vec <- strsplit(s,split=",")[[1]] 
  vec <- vec[vec !="NA"] 
  vec %>% length(.)}) %>% as.integer(.)

tab2.df <- arrange(tab2.df,metabolite)

  tt3 <- ttheme_minimal(
    core=list(bg_params = list(fill = blues9[1:2], col=NA),
            fg_params=list(fontface=3)),
    colhead=list(fg_params=list(col="navyblue", fontface=4L)),
    rowhead=list(fg_params=list(col="white", fontface=3L)))
  tab2.df$zscore <- map(tab2.df$zscore, function(n){signif(n,3)}) %>% as.numeric(.)
  tab2.df$pvalue <- map(tab2.df$pvalue, function(n){signif(n,3)}) %>% as.numeric(.)
  tab2.df$FDR_studywide <- map(tab2.df$FDR_studywide, function(n){signif(n,3)}) %>% as.numeric(.)

  tabgrob <- tableGrob(tab2.df,theme=tt3)
  grid.draw(tabgrob)
```


# Summary 

```{r}

numer <- (filter(sub,known==FALSE,hmdb==TRUE)$gene_name %>% unique(.) %>% length(.)) 
denom <- filter(sub,known==FALSE)$gene_name %>% unique(.) %>% length(.)
num.nov.hmdb <- numer/denom # 0.2742616

numer <- tab2.df$gene_name %>% unique(.) %>% length(.)
num.nov.sharepath <- numer/denom # 0.039 or 4% 
```



